// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tXtxfUL95PU6ZxWcFtpsj
// Component: STNY5B6ToE7
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ActionButton from "../../ActionButton"; // plasmic-import: Kw25oLZaMx3/component
import Spacer from "../../Spacer"; // plasmic-import: mMfpdSZguarx/component
import Avatar from "../../Avatar"; // plasmic-import: r-Q4nz0OELxu/component
import Button from "../../Button"; // plasmic-import: upJGYFxFWp8T/component
import Tweet from "../../Tweet"; // plasmic-import: Q-5iAFzkJ6TL/component
import SideSection from "../../SideSection"; // plasmic-import: BjOUYhoMAIAL/component
import Trend from "../../Trend"; // plasmic-import: WunYD34zulRt/component
import Suggestion from "../../Suggestion"; // plasmic-import: eRqh1eQb-6HI/component

import { useScreenVariants as useScreenVariantsssck4N6JFfwz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ssck4n6jFFWZ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_twitter.module.css"; // plasmic-import: tXtxfUL95PU6ZxWcFtpsj/projectcss
import sty from "./PlasmicFeed.module.css"; // plasmic-import: STNY5B6ToE7/css

import MagicIcon from "./icons/PlasmicIcon__Magic"; // plasmic-import: C3UjrcN8V9KZ/icon
import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: w2TQpvra_Nu6/icon
import HomeActiveIcon from "./icons/PlasmicIcon__HomeActive"; // plasmic-import: -58QEFr-4_PC/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: OnBuCrEPK8Rq/icon
import NotificationsIcon from "./icons/PlasmicIcon__Notifications"; // plasmic-import: bW6mT44oKghZ/icon
import MessagesIcon from "./icons/PlasmicIcon__Messages"; // plasmic-import: dm-NNlG2qyV4/icon
import BookmarksIcon from "./icons/PlasmicIcon__Bookmarks"; // plasmic-import: XhMaiKa9COze/icon
import ListsIcon from "./icons/PlasmicIcon__Lists"; // plasmic-import: gVYcjJBPlD4E/icon
import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: kQEpsncrRMWj/icon
import MoreIcon from "./icons/PlasmicIcon__More"; // plasmic-import: fKVInPMYhlh-/icon
import PictureIcon from "./icons/PlasmicIcon__Picture"; // plasmic-import: 8qjhSLA5Q0Eg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: K-KDszTh355b/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: JFjyuoC_pTUp/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: DiibcFprWh4F/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: ZkdN3HP0Bh_S/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: nvD_7SSA81fF/icon

export type PlasmicFeed__VariantMembers = {};

export type PlasmicFeed__VariantsArgs = {};
type VariantPropType = keyof PlasmicFeed__VariantsArgs;
export const PlasmicFeed__VariantProps = new Array<VariantPropType>();

export type PlasmicFeed__ArgsType = {};
type ArgPropType = keyof PlasmicFeed__ArgsType;
export const PlasmicFeed__ArgProps = new Array<ArgPropType>();

export type PlasmicFeed__OverridesType = {
  root?: p.Flex<"div">;
  avatar?: p.Flex<typeof Avatar>;
  newTweetInput?: p.Flex<"textarea">;
  tweetButton?: p.Flex<typeof Button>;
  tweetList?: p.Flex<"div">;
  searchInput?: p.Flex<"input">;
};

export interface DefaultFeedProps {}

function PlasmicFeed__RenderFunc(props: {
  variants: PlasmicFeed__VariantsArgs;
  args: PlasmicFeed__ArgsType;
  overrides: PlasmicFeed__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsssck4N6JFfwz()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___3YvIx)}>
            <div className={classNames(projectcss.all, sty.freeBox__j7Ul)}>
              {(
                hasVariant(globalVariants, "screen", "desktop") ? false : true
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__i5QPy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___52By8)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__u8Cz2)}
                      displayHeight={"30px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"30px" as const}
                      src={{
                        src: "/plasmic/twitter/images/image2.png",
                        fullWidth: 225,
                        fullHeight: 223,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j55Ud
                    )}
                  >
                    {"Home"}
                  </div>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__fo6ZQ
                    )}
                    options={["medium", "primary"]}
                    slot={"25"}
                  >
                    <MagicIcon
                      className={classNames(projectcss.all, sty.svg___7Axfo)}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__wzCit)}>
                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__r6Atl
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <TwitterIcon
                      className={classNames(projectcss.all, sty.svg__zz1Hn)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton___2JKy1
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <HomeActiveIcon
                      className={classNames(projectcss.all, sty.svg__klDth)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__glj8
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__f1Dwa)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__srxmu
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <NotificationsIcon
                      className={classNames(projectcss.all, sty.svg___10Cz)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__muHsd
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MessagesIcon
                      className={classNames(projectcss.all, sty.svg__htI50)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__mj2Fm
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <BookmarksIcon
                      className={classNames(projectcss.all, sty.svg__ezdNf)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__c147W
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ListsIcon
                      className={classNames(projectcss.all, sty.svg___3LkEq)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__xGuLb
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ProfileIcon
                      className={classNames(projectcss.all, sty.svg__yMhk)}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__vqUqz
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MoreIcon
                      className={classNames(projectcss.all, sty.svg__zhEQp)}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__hc2Ch)}>
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__hFgU)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zN47F)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qMos1
                      )}
                    >
                      {"Home"}
                    </div>

                    <Spacer
                      className={classNames(
                        "__wab_instance",
                        sty.spacer___9A4th
                      )}
                    />

                    <ActionButton
                      className={classNames(
                        "__wab_instance",
                        sty.actionButton__qIra
                      )}
                      options={["medium", "primary"]}
                      slot={"25"}
                    >
                      <MagicIcon
                        className={classNames(projectcss.all, sty.svg__wdyl7)}
                        role={"img"}
                      />
                    </ActionButton>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xhwGl)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__fIqQo)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__je4Wt
                        )}
                      >
                        <Avatar
                          data-plasmic-name={"avatar"}
                          data-plasmic-override={overrides.avatar}
                          className={classNames("__wab_instance", sty.avatar)}
                        />
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__xuk8G)}
                    >
                      <textarea
                        data-plasmic-name={"newTweetInput"}
                        data-plasmic-override={overrides.newTweetInput}
                        className={classNames(
                          projectcss.all,
                          projectcss.textarea,
                          sty.newTweetInput
                        )}
                        placeholder={"What's happening?" as const}
                        rows={1 as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4XQuU
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lqTwu
                          )}
                        >
                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__jMzJu
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <PictureIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__alMHa
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__sQlsF
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon3Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__kpL5
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__f1Xpx
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon4Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__pwsVd
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__rDtM7
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon5Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__o3ZrY
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__vBqWs
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__zlTeL
                              )}
                              role={"img"}
                            />
                          </ActionButton>
                        </p.Stack>

                        <Spacer
                          className={classNames(
                            "__wab_instance",
                            sty.spacer__b00Wb
                          )}
                        />

                        <Button
                          data-plasmic-name={"tweetButton"}
                          data-plasmic-override={overrides.tweetButton}
                          className={classNames(
                            "__wab_instance",
                            sty.tweetButton
                          )}
                          options={["primary"]}
                        >
                          {"Tweet"}
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}

              <div
                data-plasmic-name={"tweetList"}
                data-plasmic-override={overrides.tweetList}
                className={classNames(projectcss.all, sty.tweetList)}
              >
                <Tweet
                  className={classNames("__wab_instance", sty.tweet___1Hihx)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet___3SAnM)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__btCc6)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/twitter/images/image4.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___8TsS3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8SwcL
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__dYf4O)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___9NhIo)}
                        displayHeight={"140px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"140px" as const}
                        src={{
                          src: "/plasmic/twitter/images/image5.png",
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fqAwm
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ovl9C
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lzd5S
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k3Xk
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__mYuNh)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wc7A0)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/twitter/images/image7.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__uTde)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet___5WguG)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__n9V6R)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/twitter/images/image4.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__trhxp)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n3DwQ
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wtv3W)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iD5Da)}
                        displayHeight={"140px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"140px" as const}
                        src={{
                          src: "/plasmic/twitter/images/image5.png",
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hYwYw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aWjZv
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__chUeA
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jcxrZ
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__mbIqg)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__mKeuY)}
                      displayHeight={"49px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"49px" as const}
                      src={{
                        src: "/plasmic/twitter/images/image7.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>
              </div>
            </div>

            {(
              hasVariant(globalVariants, "screen", "desktop") ? true : false
            ) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aCn2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__rYfd1)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gxZqC)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oPdnW)}
                    >
                      <SearchIcon
                        className={classNames(projectcss.all, sty.svg__sEcin)}
                        role={"img"}
                      />
                    </div>

                    <input
                      data-plasmic-name={"searchInput"}
                      data-plasmic-override={overrides.searchInput}
                      className={classNames(
                        projectcss.all,
                        projectcss.input,
                        sty.searchInput
                      )}
                      placeholder={"Search Twitter" as const}
                      size={1 as const}
                      type={"text" as const}
                    />
                  </div>
                </div>

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__dsKnQ
                  )}
                  slot={
                    <React.Fragment>
                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__xqOdN
                        )}
                        slot={"Entertainment"}
                      >
                        {
                          "Adele shares photo supporting Beyoncé's Black is King"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__yzkI
                        )}
                        slot={"COVID-19"}
                      >
                        {
                          "Thousands march in Berlin to protest COVID-19 restrictions"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__gRxxf
                        )}
                        slot={"World nenws"}
                      >
                        {
                          "Russia banned from using its name, flag and anthem at the next two Olympic Games"
                        }
                      </Trend>
                    </React.Fragment>
                  }
                />

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__vNaZb
                  )}
                  slot={
                    <React.Fragment>
                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion___7CjpL
                        )}
                        slot={"Mark Dalgleish      "}
                        slot2={"@markdalgleish"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yri24)}
                          displayHeight={"49px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"49px" as const}
                          src={{
                            src: "/plasmic/twitter/images/image6.png",
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined
                          }}
                        />
                      </Suggestion>

                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion__tj58U
                        )}
                        slot={"Guillermo Rauch  "}
                        slot2={"@rauchg"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__sc6Ss)}
                          displayHeight={"49px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"49px" as const}
                          src={{
                            src: "/plasmic/twitter/images/image8.png",
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined
                          }}
                        />
                      </Suggestion>
                    </React.Fragment>
                  }
                >
                  {"Who to follow"}
                </SideSection>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6TZff)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jFsiU)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__rboKg
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Terms"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__c9MNe
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Privacy policy"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__ihbyw
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Cookies"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___6R0Or
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Ads info"}
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bKxiX)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Dhpp
                      )}
                    >
                      {"© 2021 Twitter, Inc."}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            ) : null}
            {(
              hasVariant(globalVariants, "screen", "desktop") ? false : true
            ) ? (
              <div className={classNames(projectcss.all, sty.freeBox__lgaPb)}>
                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__qN00
                  )}
                  options={["medium", "primary"]}
                  slot={"25"}
                >
                  <HomeActiveIcon
                    className={classNames(projectcss.all, sty.svg___42Bm5)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__pzmyJ
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <SearchIcon
                    className={classNames(projectcss.all, sty.svg__iK36G)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__fVrvf
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <NotificationsIcon
                    className={classNames(projectcss.all, sty.svg__qwXjH)}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton___5Zk07
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <MessagesIcon
                    className={classNames(projectcss.all, sty.svg__zLecj)}
                    role={"img"}
                  />
                </ActionButton>
              </div>
            ) : null}
            {false ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__bGtYn)}
                displayHeight={"731px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"411px" as const}
                src={{
                  src: "/plasmic/twitter/images/image.png",
                  fullWidth: 1079,
                  fullHeight: 1919,
                  aspectRatio: undefined
                }}
              />
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "avatar",
    "newTweetInput",
    "tweetButton",
    "tweetList",
    "searchInput"
  ],
  avatar: ["avatar"],
  newTweetInput: ["newTweetInput"],
  tweetButton: ["tweetButton"],
  tweetList: ["tweetList"],
  searchInput: ["searchInput"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  avatar: typeof Avatar;
  newTweetInput: "textarea";
  tweetButton: typeof Button;
  tweetList: "div";
  searchInput: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeed__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFeed__VariantsArgs;
    args?: PlasmicFeed__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFeed__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFeed__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeed__ArgProps,
      internalVariantPropNames: PlasmicFeed__VariantProps
    });

    return PlasmicFeed__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeed";
  } else {
    func.displayName = `PlasmicFeed.${nodeName}`;
  }
  return func;
}

export const PlasmicFeed = Object.assign(
  // Top-level PlasmicFeed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    avatar: makeNodeComponent("avatar"),
    newTweetInput: makeNodeComponent("newTweetInput"),
    tweetButton: makeNodeComponent("tweetButton"),
    tweetList: makeNodeComponent("tweetList"),
    searchInput: makeNodeComponent("searchInput"),

    // Metadata about props expected for PlasmicFeed
    internalVariantProps: PlasmicFeed__VariantProps,
    internalArgProps: PlasmicFeed__ArgProps
  }
);

export default PlasmicFeed;
/* prettier-ignore-end */
